[build]
  publish = "dist"               # your Vite build output
  functions = "netlify/functions" # path to functions

[dev]
  functions = "netlify/functions" # optional: run functions locally with netlify dev
